### ISSUE TITLE
Shifter: connect to existing joints

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#13]
Connect to existing joints, instead of creating  new joints

NOTE: need to freeze joints rotations  before connect

- [x] expose as an option in the guide parameters

**Comment by thirstydevil** [comment]
Hi @miquelcampos 

This is an interesting option.  We sort of doing this already with a post-process.  We find a skeleton file based on our pipeline path logic and reference into the scene in the namespace "SKEL:" then "bind" or "connect" depending on your needs; the referenced joints.

We generate the skeleton file after making the rig so that we can do skin updates independently and also swap it out to any other SKEL: file without having to rebuild the rig at all.  This logic is similar to the game exporter you have in mGear.

Sometimes you want a "direct connection" method and other times you want to maintain the offset when binding.  This gives you some wiggle room to use the same rig on deff skel files if there are just minor adjustments to joint positions.

I'm not sure how you'd make this work as an option in the guide of if the idea is compatible with your thoughts.  It's very useful if the file deformation file can be separated for ease of outsourcing, cleanliness of export to the engine.

**Comment by miquelcampos** [comment]
![image](https://user-images.githubusercontent.com/1050212/125558571-c84d94ee-ed1b-478b-af00-03d81a210627.png)

**Comment by miquelcampos** [comment]
@thirstydevil  The current implementation will maintain the offset with the joints. The only request is that the joints should have the rotation values to 0,0,0

![image](https://user-images.githubusercontent.com/1050212/125558905-fe30209f-aafe-41c9-88ee-645fd2a4e41a.png)

Also will add missing joints
![image](https://user-images.githubusercontent.com/1050212/125559019-30b78366-15ff-4908-a785-ce8543036fe3.png)
