### ISSUE TITLE
Metahuman driver neck bones not driven by mGear EPIC Metahuman rig

### ISSUE THREAD

**Issue by nevenincs** [mgear-dev/mgear#232]
I could be misunderstanding the control/driver relations but to it seems like the default Metahuman mGear rig is not attaching itself to the *neck_01_drv* and *neck_02_drv* bones.

Symptom:
The EPIC Metahuman template (z-up, didn't test y-up) controls neck_C0_fk0_ctl and neck_C0_fk1_ctl don't affect the corresponding driver joints. The head is moving correctly but the neck_0x_drv joints are not linked to any controls.

Expected behaviour:
I fixed it by manually creating mgear_matrixConstraints that take the neck fk controls and neck driver joints as inputs.

![image](https://github.com/mgear-dev/mgear4/assets/11316825/21193935-5725-4751-926e-6489c8052d9c)

Would be nice to check this against the Metahuman rig and implement an automatic fix.
Thank you!

**Comment by miquelcampos** [comment]
@wgergely Thanks for the feedback! I will check this ASAP

**Comment by miquelcampos** [comment]
@wgergely I have checked this and I can't reproduce it with the latest mGear version. Maybe It was fixed with another ticket, since many changes have been made in this area
![2023-09-01_12h27_16](https://github.com/mgear-dev/mgear4/assets/1050212/75afbac7-e4b7-4737-acfd-731407e749bf)

I am closing the ticket, Please check again with the next release 4.1 will be available very soon. Thanks

**Comment by nevenincs** [comment]
🎉 Thanks Miquel, I'll test it too. I'll have to check which version we're on at the moment (probably behind the master).
