### ISSUE TITLE
Shifter: Ik/Fk switch/snap poole vector solving

### ISSUE THREAD

**Issue by jdrese** [mgear-dev/mgear#27]
Handle the Pole Vector position as suggested by @chris-lesage

**Comment by thirstydevil** [comment]
Hi @miquelcampos I've submitted a merge request that fixes the calculation for our rigs.  I think it's done with a minimal amount of code changes.  Although I did refactor the 4 repeated code blocks into 2 functions just to reduce noise.
https://github.com/mgear-dev/mgear_core/pull/87

**Comment by miquelcampos** [comment]
Thanks @thirstydevil  I will review and merge it ASAP.

**Comment by miquelcampos** [comment]
@thirstydevil  thanks again for the PR
I have merged it manually in the mGear4 repo.
I have found a bug while collecting the lists for the ikRot ctl. Because was appending a list to another list instead of extending it
around the line 1835
I fixed by checking first if is a list, and for my tests looks like is working
```   def ik_definition():
            src_nodes = self.ikTarget + self.upvTarget
            key_nodes = self.fkCtrls
            dst_nodes = self.ikCtrl + self.upvCtrl
            if ikRot:
                if isinstance(self.ikRotTarget, list):
                    src_nodes.extend(self.ikRotTarget)
                else:
                    src_nodes.append(self.ikRotTarget)
                if isinstance(self.ikRotCtl, list):
                    key_nodes.extend(self.ikRotCtl)
                else:
                    key_nodes.append(self.ikRotCtl)
```
I am not making more releases for 3.7 so you may want to check this on your side

btw: I will archive all the 3.7 repos soon. if you have more PR please do it on the mgear4 repo. Thanks!!
